name: CI
on:
  push:
    paths:
    - 'src/**'
    -  '.github/workflows/**'
  pull_request:
    paths: 'src/**'

jobs:
  buildJob:
    name: Compile, test & Dockerize
    runs-on: ubuntu-latest
    env:
      BUILDPROJECTS: 'Gazorpazorpfield.sln'
      TESTPROJECTS: 'Gazorpazorpfield.sln'
      PUBLISHPROJECTS: 'src/CentralFiniteCurve.Gazorpazorpfield.API/CentralFiniteCurve.Gazorpazorpfield.API.csproj'
      ASSEMBLY_VERSION: '1.0.0'
      CONFIGURATION: Release
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.101
      - name: dotnet restore
        run: dotnet restore $BUILDPROJECTS
      - name: dotnet build
        run: dotnet build $BUILDPROJECTS --configuration $CONFIGURATION /p:Version=$ASSEMBLY_VERSION --no-restore
      - name: dotnet test
        run: dotnet test $TESTPROJECTS --configuration $CONFIGURATION --no-build
      - name: dotnet publish
        run: dotnet publish $PUBLISHPROJECTS --configuration $CONFIGURATION --no-build --output $GITHUB_WORKSPACE/publish/
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: files
          path: publish/
      - name: Docker Login
        if: github.ref == 'refs/heads/master'
        uses: Azure/docker-login@v1
        with:
#          login-server: myregistry.azurecr.io 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        if: github.ref == 'refs/heads/master'
        env:
          DOCKERCONTEXT: 'publish/'
          DOCKERFILE: 'src/Dockerfile.AzureDevOps'
          DOCKERIMAGE: 'anderslybecker/gazorpazorpfield'
        run: |
          docker build $DOCKERCONTEXT -f $DOCKERFILE -t $DOCKERIMAGE:$ASSEMBLY_VERSION
          docker push $DOCKERIMAGE:$ASSEMBLY_VERSION
